name: Deploy

on:
  push:
    branches: [production]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - id: branch
        run: echo "::set-output name=name::${GITHUB_REF##*}"
      - run: echo "Mona the ${{ steps.branch.outputs.name }}"

