name: Deploy

on:
  push:
    branches: [production]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_CONTEXT}
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}


