name: Deploy

on:
  push:
    branches: 
      - production
      - test

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_REF##*/}"
      - id: branch
        run: echo "::set-output name=name::${GITHUB_REF##*/}"
      - run: echo "Mona the ${{ steps.branch.outputs.name }}"

