name: Deploy each Evironment

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate release context
        id: release_context
        run: |
          tag="$(git describe HEAD --abbrev=0 --tags)"
          echo "tag_name=$tag" >>$GITHUB_OUTPUT
          echo "version=${tag/v/}" >>$GITHUB_OUTPUT
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: pr.yml
          workflow_conclusion: success
          name: "release-note-${{ steps.release_context.outputs.tag_name }}"
      - run: cat RELEASE_BODY.md
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.release_context.outputs.tag_name }}
          tag_name: ${{ steps.release_context.outputs.tag_name }}
          body_path: RELEASE_BODY.md
          prerelease: ${{ contains(github.ref_name, 'alpha') && 'development' || 'production' }}
