name: Deploy each Evironment

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/tags/v') && 'pdocution' || 'development' }}
    steps:
      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.ref }}
