name: Deploy each Evironment

on:
  push:
    tags: ["*"]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        env:
          - "development"
          - "production"
    runs-on: ubuntu-latest
    # environment: ${{ matrix.env }}
    steps:
      - run: |
          echo "Environment: $ENVIRONMENT"
        env:
          ENVIRONMENT: ${{ matrix.env }}