name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - !production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_CONTEXT}
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

