name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - v
  pull_request:
    paths-ignore:
      - v

jobs:
  build:
    if: github.base_ref != 'production'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_CONTEXT}
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

