name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches-ignore: [production]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.base_ref }}

