name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - 'vv/**'
  pull_request:
    paths-ignore:
      - 'vv/**'

jobs:
  build:
    strategy:
      matrix:
        title:
          - foo
          - bar
    if: ${{ !contains(fromJSON('["development", "production"]'), github.base_ref) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_CONTEXT}
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

