name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - 'vv/**'
  pull_request:
    paths-ignore:
      - 'vv/**'

jobs:
  build:
    if: ${{ !contains(fromJSON('["development", "production"]'), github.base_ref) }}
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        uses: wxdlong/hello-action@v7
        with:
          who-to-greet: 'Mona the ${{ github.ref }}'

