name: Release

on:
  deployment_status

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ steps.get_version.outputs.name }}
          tag_name: ${{ steps.get_version.outputs.name }}
          body_path: RELEASE_BODY.md