name: Release

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - run: cat a
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/tags/v'
    needs:
      - publish
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.base_ref }}
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - run: npm install -g conventional-changelog-cli
      - name: Conventional Changelog Action
        id: changelog
        run: |
          changelog="$(conventional-changelog -n release-options.json)"
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::${changelog}"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: main
          draft: true
          body: ${{ steps.changelog.outputs.changelog }}
