on:
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: 'Environment to run tests against'
    #     type: environment
    #     required: true

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        env:
          - "development"
          - "production"
    runs-on: ubuntu-latest
    # environment: ${{ github.event.inputs.environment }}
    environment: ${{ matrix.env }}
    steps:
      - run: |
          echo "Environment: $ENVIRONMENT"
        env:
          ENVIRONMENT: ${{ environment }}
