name: Release

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - run: cat a
  release-draft:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - publish
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: "true"
          output-file: "false"
          config-file-path: "release-options.json"
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: main
          draft: true
          body: ${{ steps.changelog.outputs.clean_changelog }}
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - publish
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - run: npm install -g github-release-notes
      - run: gren release -o -B -D "commits" --tags "${GITHUB_REF##*/}" -N commits
        env:
          GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}