name: Tagging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        uses: hashicorp/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Setting up git config
        run: |
          git config --global user.name "Takeru Sato"
          git config --global user.email "type.in.type@gmail.com"
          git config --global user.signingkey "${{ secrets.GPG_KEY_ID }}"
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - run: yarn
      - name: Generate prerelease tag and release body
        run: |
          npx standard-version -i RELEASE_BODY.md --skip.commit --skip.tag --prerelease alpha
          git restore package.json
          npx standard-version --sign --skip.changelog --prerelease alpha
        if: ${{ inputs.environment == 'development' }}
      - name: Generate tag and release body
        run: |
          npx standard-version -i RELEASE_BODY.md --skip.commit --skip.tag
          git restore package.json
          npx standard-version --sign --skip.changelog
        if: ${{ inputs.environment == 'production' }}
      - name: Publish tag
        id: publish_tag
        run: |
          git push --follow-tags
          echo "tag_name=$(git describe HEAD --abbrev=0)" >>$GITHUB_OUTPUT
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ steps.publish_tag.outputs.tag_name }}
          tag_name: ${{ steps.publish_tag.outputs.tag_name }}
          body_path: RELEASE_BODY.md
