name: Tagging

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'chore(release):') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: show event
        run: echo "${{ toJSON(github.event.head_commit.message) }}"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_committer_name: "Takeru Sato"
          git_committer_email: "type.in.type@gmail.com"
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - run: yarn
      - name: Generate prerelease tag and release body
        if: ${{ github.job.environment != 'production' }}
        run: |
          npx standard-version -i RELEASE_BODY.md --skip.commit --skip.tag --prerelease alpha
          git restore package.json
          npx standard-version --sign --skip.changelog --prerelease alpha
      - name: Generate tag and release body
        if: ${{ github.job.environment == 'production' }}
        run: |
          npx standard-version -i RELEASE_BODY.md --skip.commit --skip.tag
          git restore package.json
          npx standard-version --sign --skip.changelog
      - name: Publish tag
        id: publish_tag
        run: |
          git push --follow-tags
          echo "tag_name=$(git describe HEAD --abbrev=0)" >>$GITHUB_OUTPUT
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.publish_tag.outputs.tag_name }}
          tag_name: ${{ steps.publish_tag.outputs.tag_name }}
          body_path: RELEASE_BODY.md
          prerelease: ${{ github.job.environment == 'production' }}
