name: Tagging

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.commits[0].message, 'chore(release):') }}
    steps:
      - run: echo '${{ toJSON(github.event.commits[0].message) }}'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_committer_name: "Takeru Sato"
          git_committer_email: "type.in.type@gmail.com"
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - run: yarn
      - name: Publish tag
        run: |
          git tag "v$(cat package.json | jq -r ".version")"
          git push --follow-tags
